<?php

/**
 * @file
 * Hook implementations for views_filters_summary_search_api module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Hook implementations for views_filters_summary_address module.
 */

/**
 * Implements hook_views_filters_summary_plugin_alias().
 */
function views_filters_summary_search_api_views_filters_summary_plugin_alias($filter) {
  switch ($filter->getPluginId()) {
    case 'search_api_term':
      return 'taxonomy_index_tid';

    case 'search_api_options':
      return 'list_field';
  }
}

/**
 * Implements hook_views_filters_summary_replacements_alter().
 */
function views_filters_summary_search_api_views_filters_summary_replacements_alter(&$replacements, $view) {
  foreach ($view->display_handler->handlers['filter'] as $filter) {
    if ($filter->getPluginId() === 'search_api_fulltext') {
      $identifier = $filter->options['expose']['identifier'];
      $exposed_data = $view->exposed_data[$identifier] ?? NULL;
      if (!empty($exposed_data)) {
        $replacements['search_api_fulltext'] = Html::escape($exposed_data);
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function views_filters_summary_search_api_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'views_ui_config_item_form') {
    $storage = $form_state->getStorage();
    if ($storage['id'] === 'views_filters_summary') {
      $item_list = [
        '#theme' => 'item_list',
        '#items' => [
          '@search_api_fulltext -- the fulltext search api filter value',
        ],
      ];
      $form['options']['content']['#description']
        .= \Drupal::service('renderer')->render($item_list);
    }
  }
}

/**
 * Implements hook_views_filters_summary_valid_index().
 */
function views_filters_summary_search_api_views_filters_summary_valid_index($index, $filter) {
  if ($filter->getPluginId() === 'search_api_options') {
    return !is_null($index);
  }
}
