<?php

/**
 * @file
 * Hook implementations for views_filters_summary_eb module.
 */

use Drupal\views\Plugin\views\display\DisplayPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_filters_summary_exposed_form_id_alter().
 */
function views_filters_summary_eb_views_filters_summary_exposed_form_id_alter(
  string &$exposed_form_id,
  ViewExecutable $view,
  DisplayPluginBase $display_handler,
) {
  if ($display_handler->getPluginId() === 'entity_browser') {
    // In an Entity Browser display, the View’s exposed filters are embedded
    // within the browser’s own form (there is no separate
    // <form id="views-exposed-form-...">). The form ID instead follows the
    // pattern: <form id="entity-browser-...">.
    $exposed_form_id = 'entity-browser-';
  }
}
