options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations:
   - 1
   -
    exclude:
      bp
      breakpoint
      mq

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks:
    - 1
    -
      include: true
      allow-single-line-rulesets: true
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 1
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 1
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties:
    - 1
    -
      exclude:
        - display
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false
  no-trailing-whitespace: 1
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 0
  no-url-protocols:
    - 1
    -
      allow-protocol-relative-urls: true
  no-vendor-prefixes: 0
  no-warn: 0
  property-units: 0

  # Nesting
  declarations-before-nesting: 1
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 1
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  function-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  id-name-format: 0
  mixin-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedbem
  placeholder-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedbem
  variable-name-format:
    - 1
    -
      allow-leading-underscore: false
      convention: hyphenatedbem

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero:
    - 1
    -
      convention: 0
  brace-style:
    - 1
    -
      style: stroustrup
      allow-single-line: true
  clean-import-paths: 0
  empty-args:
    - 1
    -
      include: false
  hex-length:
    - 1
    -
      style: short
  hex-notation:
    - 1
    -
      style: lowercase
  indentation:
    - 1
    -
      size: 2
  leading-zero:
    - 1
    -
      include: false
  max-line-length:
    - 1
    -
      length: 80
  max-file-line-count: 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  property-sort-order:
    - 1
    -
      order: alphabetical
  pseudo-element: 0
  quotes:
    - 1
    -
      style: double
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 0
  zero-unit:
    - 1
    -
      include: false

  # Inner Spacing
  space-after-comma:
    - 1
    -
      include: true
  space-before-colon:
    - 1
    -
      include: false
  space-after-colon:
    - 1
    -
      include: true
  space-before-brace:
    - 1
    -
      include: true
  space-before-bang:
    - 1
    -
      include: true
  space-after-bang:
    - 1
    -
      include: false
  space-between-parens:
    - 1
    -
      include: false
  space-around-operator:
    - 1
    -
      include: true

  # Final Items
  trailing-semicolon: 1
  final-newline:
    - 1
    -
      include: true
