views.field.event_evaluation_criteria_count:
  type: views.field.numeric
  label: 'Event evaluation criteria count'

views.field.event_evaluation_negative_count:
  type: views.field.numeric
  label: 'Event evaluation negative count'

views.field.event_evaluation_positive_count:
  type: views.field.numeric
  label: 'Event evaluation positive count'

views.field.event_attendance_count:
  type: views.field.numeric
  label: 'Event attendance count'

views.field.event_registration_count:
  type: views.field.numeric
  label: 'Event registration count'

views.filter.numeric_reference:
  type: views.filter.numeric
  label: 'Numeric reference'
  mapping:
    expose:
      type: mapping
      label: 'Exposed'
      mapping:
        min_placeholder:
          type: label
          label: 'Min placeholder'
        max_placeholder:
          type: label
          label: 'Max placeholder'
        placeholder:
          type: label
          label: 'Placeholder'
    handler:
      type: string
      label: 'Selection handler'
      nullable: false
      translatable: false
    handler_settings:
      type: entity_reference_selection.default
      label: 'Selection handler settings'
    handler_submit:
      type: string
      label: 'Change handler'
    value:
      type: views.filter_value.in_operator
      label: 'Value'
    widget:
      type: string
      label: 'Selection type'
      nullable: false
      translatable: false

views.relationship.vote_relationship:
  type: views_relationship
  label: 'Display options for vote relationship'
  mapping:
    vote:
      type: string
      label: 'The vote'
    user_scope:
      type: string
      label: 'The user scope'
