# CKE5
ckeditor5.plugin.video_embed_wysiwyg_video_embed:
  label: 'Video Embed'
  type: mapping
  mapping:
    defaults:
      label: 'Defaults'
      type: mapping
      mapping:
        children:
          label: 'Children'
          type: mapping
          mapping:
            autoplay:
              label: 'Autoplay'
              type: boolean
            responsive:
              label: 'Responsive'
              type: boolean
            width:
              label: 'Width'
              type: string
            height:
              label: 'Height'
              type: string
            title_format:
              type: label
              label: 'Title format'
            title_fallback:
              type: boolean
              label: 'Use a fallback title'
