block.settings.views_exposed_filter_blocks_block:
  type: block_settings
  label: 'Views exposed filter block'
  mapping:
    view_display:
      type: string
      label: 'View & Display'
    form_state_always_process:
      type: boolean
      label: 'Always process the form state (on block build)'