views.filter.intercept_entity_reference:
  type: views.filter.many_to_one
  label: 'Intercept entity reference'
  mapping:
    handler:
      type: string
      label: 'Selection handler'
      nullable: false
      translatable: false
    widget:
      type: string
      label: 'Selection type'
      nullable: false
      translatable: false
    list_max:
      type: integer
      label: 'Maximum entities in select list'
      nullable: false
      translatable: false
    handler_settings:
      type: entity_reference_selection.default
      label: 'Selection handler settings'
      mapping:
        target_bundles:
          type: sequence
          label: 'types'
          nullable: true
          sequence:
            type: string
            label: 'Bundle'
        sort:
          type: mapping
          label: 'Sort settings'
          mapping:
            field:
              type: string
              label: 'Sort by'
            direction:
              type: string
              label: 'Sort direction'
        auto_create:
          type: boolean
          label: 'Create referenced entities if they don''t already exist'
        auto_create_bundle:
          type: string
          label: 'Bundle assigned to the auto-created entities.'
        view:
          type: mapping
          label: 'View used to select the entities'
          mapping:
            view_name:
              type: string
              label: 'View name'
            display_name:
              type: string
              label: 'Display name'
            arguments:
              type: sequence
              label: 'View arguments'
              sequence:
                type: string
                label: 'Argument'
    handler_submit:
      type: string
      label: 'Change handler'
    expose:
      type: mapping
      label: 'Exposed'
      mapping:
        placeholder:
          type: label
          label: 'Placeholder'
