<?php

/**
 * @file
 * Module file for dynamic_entity_reference_entity_test.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\dynamic_entity_reference_entity_test\Hook\DynamicEntityReferenceEntityTestHooks;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function dynamic_entity_reference_entity_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  return \Drupal::service(DynamicEntityReferenceEntityTestHooks::class)->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_views_data().
 */
#[LegacyHook]
function dynamic_entity_reference_entity_test_views_data() {
  return \Drupal::service(DynamicEntityReferenceEntityTestHooks::class)->viewsData();
}
