name: 'Charts API Example'
type: module
description: 'Demonstrates how to use the Charts module without Views.'
core_version_requirement: ^10.3 || ^11 || ^12
package: Examples
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2026-08-04
version: '5.2.3'
project: 'charts'
datestamp: 1785875201
