<?php

/**
 * @file
 * Charts API Example module file.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function charts_api_example_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('charts_api_example.hooks')->help($route_name, $route_match);
}
