charts_billboard_api_example.display:
  path: /charts/example/billboard
  defaults:
    _controller: '\Drupal\charts_billboard_api_example\Controller\BillboardApiExample::display'
    _title: 'Billboard.js API Example'
  requirements:
    _permission: 'access content'
