<?php

/**
 * @file
 * Hook implementations for views_filters_summary_vsf module.
 */

use Drupal\views\Plugin\views\filter\FilterPluginBase;
use Drupal\views_selective_filters\Plugin\views\filter\Selective;

/**
 * Implements hook_views_filters_summary_info_alter().
 */
function views_filters_summary_vsf_views_filters_summary_info_alter(array &$info, FilterPluginBase $filter) {

  if (!($filter instanceof Selective) || !is_array($info['value'])) {
    return;
  }

  $values = [];

  foreach ($filter->value as $index => $index_value) {
    // Skip not selected options.
    if ($index != $index_value) {
      continue;
    }

    $value_options = $filter->getValueOptions();
    $value = $value_options[$index_value];

    $values[] = [
      'id' => $index,
      'raw' => (string) $index,
      'value' => $value,
    ];
  }

  $info['value'] = $values;
}
