################
# DrupalCI GitLabCI template
#
# Gitlab-ci.yml to replicate DrupalCI testing for Contrib
#
# With thanks to:
#   * The GitLab Acceleration Initiative participants
#   * DrupalSpoons
################

################
# Guidelines
#
# This template is designed to give any Contrib maintainer everything they need to test, without requiring modification. It is also designed to keep up to date with Core Development automatically through the use of include files that can be centrally maintained.
#
# However, you can modify this template if you have additional needs for your project.
################

################
# Includes
#
# Additional configuration can be provided through includes.
# One advantage of include files is that if they are updated upstream, the changes affect all pipelines using that include.
#
# Includes can be overridden by re-declaring anything provided in an include, here in gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/yaml/includes.html#override-included-configuration-values
################

include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

################
# Pipeline configuration variables
#
# These are the variables provided to the Run Pipeline form that a user may want to override.
#
# Docs at https://git.drupalcode.org/project/gitlab_templates/-/blob/1.0.x/includes/include.drupalci.variables.yml
################
variables:
  _CSPELL_IGNORE_PATHS: 'tests/fixtures/*'
  # _PHPUNIT_CONCURRENT=1 uses run-tests.sh, 0 uses phpunit directly.
  _PHPUNIT_CONCURRENT: 1

# Job overrides
composer:
  extends: .composer-base
  variables:
    DRUPAL_CORE: "11.3.x"
    IGNORE_PROJECT_DRUPAL_CORE_VERSION: 1
    PHP_VERSION: "8.4"
    PHP_IMAGE_VARIANT: "ubuntu-apache"

cspell:
  allow_failure: false

phpcs:
  allow_failure: false

#
# Manual builds (all other combinations)
#

## Drupal 11 (next minor)
composer-d11_next:
  stage: build
  extends: .composer-base
  variables:
    DRUPAL_CORE: "11.x-dev"
    MINIMUM_STABILITY_OVERRIDE: 'dev'
    IGNORE_PROJECT_DRUPAL_CORE_VERSION: 1
    PHP_VERSION: "8.4"
    PHP_IMAGE_VARIANT: "ubuntu-apache"
  dependencies: []
  rules:
    - when: manual
  allow_failure: true

## Drupal 10.6
composer-d10_6:
  stage: build
  extends: .composer-base
  variables:
    DRUPAL_CORE: "10.6.x"
    IGNORE_PROJECT_DRUPAL_CORE_VERSION: 1
    PHP_VERSION: "8.3"
    PHP_IMAGE_VARIANT: "ubuntu-apache"
  dependencies: []
  rules:
    - when: manual
  allow_failure: true

## Drupal 10.5
composer-d10_5:
  stage: build
  extends: .composer-base
  variables:
    DRUPAL_CORE: "10.5.x"
    IGNORE_PROJECT_DRUPAL_CORE_VERSION: 1
    PHP_VERSION: "8.2"
    PHP_IMAGE_VARIANT: "apache"
  dependencies: []
  rules:
    - when: manual
  allow_failure: true

## Drupal 9.5
composer-d9_5:
  stage: build
  extends: .composer-base
  variables:
    DRUPAL_CORE: "9.5.x"
    IGNORE_PROJECT_DRUPAL_CORE_VERSION: 1
    PHP_VERSION: "8.1"
    PHP_IMAGE_VARIANT: "apache"
    COMPOSER_AUDIT_BLOCK_INSECURE: false
  dependencies: []
  rules:
    - when: manual
  allow_failure: true

## Drupal 8.9
composer-d8_9:
  stage: build
  extends: .composer-base
  variables:
    DRUPAL_CORE: "8.9.x"
    IGNORE_PROJECT_DRUPAL_CORE_VERSION: 1
    PHP_VERSION: "7.4"
    PHP_IMAGE_VARIANT: "apache"
    COMPOSER_AUDIT_BLOCK_INSECURE: false
  dependencies: []
  rules:
    - when: manual
  allow_failure: true

#
# Manual validate jobs
#

phpstan-d11_next:
  extends: .phpstan-base
  stage: validate
  needs:
    - composer-d11_next
  allow_failure: true
  rules:
    - when: manual

phpstan-d10_6:
  extends: .phpstan-base
  stage: validate
  needs:
    - composer-d10_6
  allow_failure: true
  rules:
    - when: manual

#
# Manual tests
#

phpunit-d11_next:
  extends: .phpunit-base
  stage: test
  needs:
    - composer-d11_next

phpunit-d11_next-all_deprecations:
  extends: .phpunit-base
  stage: test
  needs:
    - composer-d11_next
  allow_failure: true
  rules:
    - when: manual
  variables:
    # Use core ignoreFile to show deprecations. This will only work with $_PHPUNIT_CONCURRENT=1
    SYMFONY_DEPRECATIONS_HELPER: "ignoreFile=$CI_PROJECT_DIR/$_WEB_ROOT/core/.deprecation-ignore.txt"

phpunit-d10_6:
  extends: .phpunit-base
  stage: test
  needs:
    - composer-d10_6

phpunit-d10_5:
  extends: .phpunit-base
  stage: test
  needs:
    - composer-d10_5

phpunit-d9_5:
  extends: .phpunit-base
  stage: test
  needs:
    - composer-d9_5

phpunit-d8_9:
  extends: .phpunit-base
  stage: test
  needs:
    - composer-d8_9
