name: 'Billboard.js Charts'
type: module
description: 'Charts module integration with Billboard.js Charts.'
package: Charts
core_version_requirement: ^9.2 || ^10
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2023-06-27
version: '5.0.7'
project: 'charts'
datestamp: 1687898053
