<?php

/**
 * @file
 * Defines common functionality for intercept_ils.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_help().
 */
function intercept_ils_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the intercept_ils module.
    case 'help.page.intercept_ils':
      $output = '';
      $output .= '<h3>' . new TranslatableMarkup('About') . '</h3>';
      $output .= '<p>' . new TranslatableMarkup('ILS integration for the Intercept library') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function intercept_ils_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  if ($entity_type->id() == 'node' && $bundle == 'location') {
    $fields['ils'] = BaseFieldDefinition::create('ils_mapping')
      ->setLabel(t('ILS Mapping'))
      ->setComputed(TRUE)
      ->setCardinality(1)
      ->setDefaultValue(FALSE);
  }

  if ($entity_type->id() == 'user') {
    $fields['ils'] = BaseFieldDefinition::create('ils_mapping')
      ->setLabel(t('ILS Mapping'))
      ->setComputed(TRUE)
      ->setCardinality(1)
      ->setDefaultValue(FALSE);
  }

  return $fields;
}
