<?php

/**
 * @file
 * Defines common functionality for intercept_ils.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_bundle_field_info().
 */
function intercept_ils_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  if ($entity_type->id() == 'node' && $bundle == 'location') {
    $fields['ils'] = BaseFieldDefinition::create('ils_mapping')
      ->setLabel(t('ILS Mapping'))
      ->setComputed(TRUE)
      ->setCardinality(1)
      ->setDefaultValue(FALSE);
  }

  if ($entity_type->id() == 'user') {
    $fields['ils'] = BaseFieldDefinition::create('ils_mapping')
      ->setLabel(t('ILS Mapping'))
      ->setComputed(TRUE)
      ->setCardinality(1)
      ->setDefaultValue(FALSE);
  }

  return $fields;
}
