votingapi.settings:
  type: config_object
  label: 'VotingApi settings'
  mapping:
    anonymous_window:
      type: integer
      label: 'Anonymous vote rollover'
      constraints:
        AllowedValues: [-1, 0, 300, 900, 1800, 3600, 10800, 21600, 32400, 43200, 86400, 172800, 345600, 604800]
    user_window:
      type: integer
      label: 'Registered user vote rollover'
      constraints:
        AllowedValues: [-1, 0, 300, 900, 1800, 3600, 10800, 21600, 32400, 43200, 86400, 172800, 345600, 604800]
    calculation_schedule:
      type: string
      label: 'Vote tallying'
      constraints:
        AllowedValues: ['immediate', 'cron', 'manual']
    delete_everywhere:
      type: boolean
      label: 'Delete everywhere'

votingapi.vote_type.*:
  type: config_entity
  label: 'Vote Type'
  mapping:
    id:
      type: machine_name
      label: 'Machine-readable name'
    label:
      type: required_label
      label: 'Name'
    value_type:
      type: string
      label: 'Type of vote value (percentage, points, etc.)'
    description:
      type: text
      label: 'Description'
