<?php

/**
 * @file
 * Contains tally.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_help().
 */
function tally_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tally module.
    case 'help.page.tally':
      $output = '';
      $output .= '<h3>' . new TranslatableMarkup('About') . '</h3>';
      $output .= '<p>' . new TranslatableMarkup('Tally') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_data().
 */
function tally_views_data() {
  $data = [];

  $data['node']['tally_filter'] = [
    'title' => t('Tally Filter'),
    'filter' => [
      'title' => t('Tally Filter'),
      'field' => 'id',
      'id' => 'tally_filter',
    ],
  ];

  return $data;
}
