<?php

/**
 * @file
 * Creates a field and widget for inserting working or office hours per day.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\office_hours\Hook\OfficeHoursFieldHooks;

// @todo Remove hook declarations from module file in D11.1.
// @see https://www.drupal.org/project/office_hours/issues/3505428
// @see https://drupalize.me/blog/drupal-111-adds-hooks-classes-history-how-and-tutorials-weve-updated
// Add hook_theme and hook_preprocess hook implementations.
include_once __DIR__ . '/office_hours.theme.inc';
// Add hook_views and hook_field_views hook implementations.
include_once __DIR__ . '/office_hours.views.inc';

/**
 * Implements hook_help() on 'help.page.office_hours'.
 */
#[LegacyHook]
function office_hours_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(OfficeHoursFieldHooks::class)->help($route_name, $route_match);
}

/**
 * Implements hook_field_type_category_info_alter().
 */
#[LegacyHook]
function office_hours_field_type_category_info_alter(&$definitions) {
  return \Drupal::service(OfficeHoursFieldHooks::class)->field_type_category_info_alter($definitions);
}

/**
 * Implements hook_office_hours_time_format_alter().
 */
function office_hours_office_hours_time_format_alter(string &$formatted_time) {
  // Only to test the alter hook in office_hours.api.php .
}

/**
 * Implements hook_office_hours_current_time_alter().
 */
function office_hours_office_hours_current_time_alter(int &$time, $entity) {
  // Only to test the alter hook in office_hours.api.php .
}
