charts_chartjs_api_example.display:
  path: /charts/example/chartjs
  defaults:
    _controller: '\Drupal\charts_chartjs_api_example\Controller\ChartjsApiExample::display'
    _title: 'Chart.js API Example'
  requirements:
    _permission: 'access content'
