<?php

/**
 * @file
 * Contains the "views_test_exposed_filter" module hooks and callbacks.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function views_test_exposed_filter_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  if (isset($form['title'])) {
    $form['title']['#ajax']['callback'] = 'views_test_exposed_filter_ajax_callback';
    $form['title']['#ajax']['wrapper'] = 'views-test-exposed-filter-test';
    $form['title']['#prefix'] = '<span id="views-test-exposed-filter-test">Default prefix</span>';
  }
}

/**
 * Returns render array via an AJAX callback for testing.
 *
 * @param array $form
 *   The form definition array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state object.
 * @return array
 *   Render array to display when the AJAX callback is triggered.
 */
function views_test_exposed_filter_ajax_callback(array &$form, FormStateInterface $form_state) {
  return [
    '#markup' => 'Callback called.',
  ];
}
