<?php

/**
 * @file
 * Hook implementations for views_filters_summary_cvfb module.
 */

/**
 * Implements hook_library_info_alter().
 */
function views_filters_summary_cvfb_library_info_alter(&$libraries, $extension) {
  if ($extension === 'views_filters_summary' && isset($libraries['views_filters_summary'])) {
    $module_path = \Drupal::service('extension.list.module')->getPath('views_filters_summary_cvfb');
    $libraries['views_filters_summary']['js']['/' . $module_path . '/js/views-filters-summary-cvfb.js'] = [];
  }
}
