include:
  # https://docs.gitlab.com/ee/ci/yaml/index.html#includetemplate
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

deploystacks:
  trigger:
    include: .drupalci/.gitlab-single-pipeline.yml
    strategy: depend
  parallel:
    matrix:
      # Drupal 10 requires PHP 8.1
      - DRUPAL_CORE_CONSTRAINT: ["10.0", "10.1"]
        PHP_VERSION: ["8.1", "8.2"]
        MYSQL_VERSION: ["8"]
        RRULE_CONSTRAINT: ["^2"]
