<?php

/**
 * @file
 * Hook implementations for views_filters_summary module.
 *
 * Provides the ability to show which filters are used in Views Result.
 */

use Drupal\views\Plugin\views\filter\FilterPluginBase;

/**
 * Implements hook_theme().
 */
function views_filters_summary_theme($existing, $type, $theme, $path): array {
  return [
    'views_filters_summary' => [
      'variables' => [
        'summary' => NULL,
        'options' => [],
        'exposed_form_id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function views_filters_summary_views_data(): array {
  $data['views']['views_filters_summary'] = [
    'title' => t('Views exposed filters summary'),
    'help' => t('Shows result summary with filters.'),
    'area' => [
      'id' => 'views_filters_summary',
    ],
  ];

  return $data;
}

/**
 * Implements hook_views_filters_summary_filter_value_alter().
 */
function views_filters_summary_views_filters_summary_filter_value_alter(
  mixed &$value,
  FilterPluginBase $filter,
) {
  // For some reason, the User Permissions plugin does not properly
  // populate the filter value.
  if ($filter->getPluginId() === 'user_permissions') {
    $inputs = $filter->view->getExposedInput();
    $value = $inputs[$filter->options['id']];
  }
}

/**
 * Implements hook_views_filters_summary_plugin_alias().
 */
function views_filters_summary_views_filters_summary_plugin_alias($filter) {
  switch ($filter->getPluginId()) {
    case 'user_permissions':
    case 'user_roles':
      return 'list_field';
  }
}
