<?php

/**
 * @file
 * Implement module related hooks for the charts_highcharts module.
 */

use Drupal\charts\ConfigUpdater;
use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_charts_version3_to_new_settings_structure_alter().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function charts_highcharts_charts_version3_to_new_settings_structure_alter(array &$new_settings, string $for, ConfigUpdater $config_updater) {
  return \Drupal::service('charts_highcharts.hooks')->chartsVersion3ToNewSettingsStructureAlter($new_settings, $for, $config_updater);
}
