name: 'Existing Values Autocomplete Widget'
type: module
description: 'Provides a widget for text fields that supplies an autocomplete callback with any previously entered (existing) values for the field.'
core_version_requirement: ^8.9 || ^9 || ^10
package: 'Other'
dependencies:
  - drupal:field
  - drupal:text

# Information added by Drupal.org packaging script on 2023-01-23
version: '2.0.0-beta1'
project: 'existing_values_autocomplete_widget'
datestamp: 1674461544
