# Schema for views exposed filters summary.
views.area.views_filters_summary:
  type: views_area
  label: 'View filters summary'
  mapping:
    filters:
      type: sequence
      label: 'The filters to show'
      sequence:
        type: string
        label: 'Field name'
    show_labels:
      type: boolean
      label: 'Show labels'
    group_values:
      type: boolean
      label: 'Group values'
    display_remove_option:
      type: boolean
      label: 'Display remove option'
    content:
      type: text
      label: 'The shown text of the result summary area'
    filters_summary_separator:
      type: string
      label: 'Exposed Filter Summary Separator'
    filters_summary_prefix:
      type: string
      label: 'Exposed Filters Summary Prefix'
    filters_result_label:
      type: mapping
      label: 'Filter result labels'
      mapping:
        plural:
          type: string
          label: 'Plural label for the type of result being shown'
        singular:
          type: string
          label: 'Singular label for the type of result being shown'
