name: 'Charts Google API Example'
type: module
description: 'Demonstrates how to use the Charts API with the Google Charts library.'
core_version_requirement: ^10.3 || ^11 || ^12
package: Examples
dependencies:
  - 'charts:charts'
  - 'charts:charts_google'
  - 'charts:charts_api_example'

# Information added by Drupal.org packaging script on 2026-06-23
version: '5.2.2'
project: 'charts'
datestamp: 1782213254
