name: 'Chart.js Charts'
type: module
description: 'Charts module integration with Chart.js.'
package: Charts
core_version_requirement: ^10.3 || ^11 || ^12
dependencies:
  - 'charts:charts'

# Information added by Drupal.org packaging script on 2026-09-14
version: '5.2.4'
project: 'charts'
datestamp: 1789402687
