<?php

/**
 * @file
 * Implement module related hooks for the charts_chartjs module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_charts_version3_to_new_settings_structure_alter().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function charts_chartjs_charts_version3_to_new_settings_structure_alter(array &$new_settings, string $for) {
  return \Drupal::service('charts_chartjs.hooks')->chartsVersion3ToNewSettingsStructureAlter($new_settings, $for);
}
