<?php

/**
 * @file
 * Charts - Module.
 */

use Drupal\charts\Hook\ChartsHooks;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function charts_theme($existing, $type, $theme, $path) {
  return \Drupal::service('charts.hooks')->theme();
}

/**
 * Implements hook_preprocess_HOOK().
 */
#[LegacyHook]
function template_preprocess_charts_chart(&$variables) {
  \Drupal::service(ChartsHooks::class)->templatePreprocessChartsChart($variables);
}

/**
 * Implements hook_views_data().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function charts_views_data() {
  return \Drupal::service('charts.hooks')->viewsData();
}

/**
 * Implements hook_views_pre_view().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function charts_views_pre_view(ViewExecutable $view, string $display_id, array &$args): void {
  \Drupal::service('charts.hooks')->viewsPreView($view, $display_id, $args);
}

/**
 * Implements hook_library_info_alter().
 *
 * @phpstan-ignore-next-line
 */
#[LegacyHook]
function charts_library_info_alter(array &$libraries, string $extension) {
  \Drupal::service('charts.hooks')->libraryInfoAlter($libraries, $extension);
}
